buid_all_targets: only build one target per inst
Freifunk-Spalter/repo_builder pull request #2
Opened 2020-11-19 16:37 UTC by PolynomialDivision

Build only 1 one target per instruction set.
Further, enable parallel building.

2020-11-20 19:43 UTC, spolack commented on build_all_targets
> +ARCHS="mediatek-mt7622 mvebu-cortexa72 layerscape-armv8_64b brcm2708-bcm2708 mxs-generic ipq806x-generic at91-sama5 sunxi-cortexa7 ipq40xx-generic sunxi-cortexa8 bcm53xx-generic zynq-generic mvebu-co
If statically mapped, please do the mapping in a dictionary with key=arch,value=instrset. Otherwise it will be hard to maintain. Furthermore the targets between openwrt versions might differ.

Best would be to fetch that dynamically from the branch somehow.

2020-11-20 19:50 UTC, spolack commented on build_feed
> +  IMAGE="openwrtorg/sdk$SDK_TAG"
This together with line 20 breaks building master branch.  You will always build using x86 image builder, no matter what arch you trying to bulild. 

I suggest you to remove that magic, There is no point in removing the tag in case of building the snapshot

2020-11-20 19:51 UTC, spolack commented on build_feed
> +  if [ "$1" == "master" ]; then SDK_TAG=""; else SDK_TAG=":$1"; fi
$1 will be never master. Please remove that magic.

2020-11-20 19:52 UTC, spolack commented on build_all_targets
> +        if [ "$OPENWRT_VERSION" == "master" ]; then DOCKER_HUB="$i"; else DOCKER_HUB="$i-$OPENWRT_VERSION"; fi
see below commits. there is no need to make it behave differently for master or snapshot branches.

2020-11-20 19:53 UTC, spolack requested changes
Please resolve the issues.

2020-12-08 18:39 UTC, PolynomialDivision commented on build_all_targets
> +ARCHS="mediatek-mt7622 mvebu-cortexa72 layerscape-armv8_64b brcm2708-bcm2708 mxs-generic ipq806x-generic at91-sama5 sunxi-cortexa7 ipq40xx-generic sunxi-cortexa8 bcm53xx-generic zynq-generic mvebu-co
How can i do this in a shell?

2020-12-08 18:39 UTC, PolynomialDivision commented on build_feed
> +  if [ "$1" == "master" ]; then SDK_TAG=""; else SDK_TAG=":$1"; fi
Why?

2020-12-19 10:45 UTC, PolynomialDivision commented
There was a failure. I removed it. Should be fine now.

2020-12-19 16:22 UTC, Akira25 commented
@PolynomialDivision we don't need the docker-flag `-i`. The documentation says it does this:
```
-i, --interactive=true|false
          Keep STDIN open even if not attached. The default is false.
```
If this flag is set, repo-builder won't run on buildbot. Technically it does not run on a shell there. Therefore -i wont work there.

2020-12-19 16:33 UTC, PolynomialDivision commented
> @PolynomialDivision we don't need the docker-flag `-i`. The documentation says it does this:
> 
> ```
> -i, --interactive=true|false
>           Keep STDIN open even if not attached. The default is false.
> ```
> 
> If this flag is set, repo-builder won't run on buildbot. Technically it does not run on a shell there. Therefore -i wont work there.

ah okay. I will test again with this flag.

2020-12-20 13:00 UTC, Akira25 commented
In overall, this looks good. This passes building in buildbot without obvious issues.
http://buildbot.berlin.freifunk.net/#/builders/47/builds/20

In step 3, where we build the packages, there are some make-errors:
```
#
# No change to .config
#
 make[1] package/index
WARNING: Applying padding in /home/build/openwrt/bin/targets/cns3xxx/generic/packages/Packages to workaround usign SHA-512 bug!
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
WARNING: Applying padding in /home/build/openwrt/bin/packages/arm_cortex-a9/base/Packages to workaround usign SHA-512 bug!
WARNING: Applying padding in /home/build/openwrt/bin/packages/arm_cortex-a9/base/Packages to workaround usign SHA-512 bug!
WARNING: Applying padding in /home/build/openwrt/bin/packages/arm_cortex-a9_neon/packages/Packages to workaround usign SHA-512 bug!
WARNING: Applying padding in /home/build/openwrt/bin/packages/arm_arm926ej-s/falter/Packages to workaround usign SHA-512 bug!
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
WARNING: Applying padding in /home/build/openwrt/bin/packages/arm_mpcore_vfp/falter/Packages to workaround usign SHA-512 bug!
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
WARNING: Applying padding in /home/build/openwrt/bin/packages/mips64_octeonplus/luci/Packages to workaround usign SHA-512 bug!
WARNING: Applying padding in /home/build/openwrt/bin/packages/mips64_octeonplus/packages/Packages to workaround usign SHA-512 bug!
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
make -r package/index: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/build/openwrt/include/toplevel.mk:228: package/index] Error 1
program finished with exit code 0
```

If they are okay, I'd like to have that merged soon. This reduces buildtime for the feed from 3h10m to rougly 20 minutes.

2020-12-20 13:00 UTC, Akira25 commented
@spolack

2020-12-25 22:27 UTC, spolack approved these changes

2020-12-25 22:34 UTC, spolack requested changes

2020-12-25 22:34 UTC, spolack commented on build_all_targets
> +        (./build_feed "${archs[${key}]}" "$FEED" "$OUTPUT_DIR" "$OPENWRT_VERSION") &
I dont like adding another argument to build_feed.

SDK_TAG contains all the information it needs to do the build. Therefore please pass the version over within SDK_TAG

2020-12-25 22:34 UTC, spolack commented on build_feed
> -  docker run --rm -it \
Thats not nice!  i'd rather like to see the parallel building to be disabled by default, instead of overwhelming ppl with thousands of docker containers in parallel.

2020-12-25 22:44 UTC, Akira25 commented on build_feed
> -  docker run --rm -it \
Okay, like we agreed on in the chat, it would be really nice to have that kind of parallel-building only activated, if we give a cmd-option for that. This way of parallel-building is really handy for buildbot.

2020-12-26 11:04 UTC, PolynomialDivision commented
Maybe we should think about writing lua script, or python script?
I'm annoyed about the bash parsing.

2020-12-26 13:31 UTC, Akira25 commented on build_feed
> +  if [ "$1" == "master" ]; then SDK_TAG=""; else SDK_TAG=":$1"; fi
I think the goal of this was to enable building the package feed against snapshot-sdk. @PolynomialDivision and I agreed on implementing that in a new version of this PR. The parameter will be named "snapshot".

2020-12-26 13:34 UTC, Akira25 commented on build_all_targets
> +        (./build_feed "${archs[${key}]}" "$FEED" "$OUTPUT_DIR" "$OPENWRT_VERSION") &
The new version preserves the call of `build_feed`

2020-12-26 16:33 UTC, Akira25 approved these changes
That worked reasonably on the [buildbot](http://buildbot.berlin.freifunk.net/#/builders/51/builds/14). The failure in the last step was an error of mine. It's an builbot issue, which doesn't bother this.

The result of this build are [here](http://buildbot.berlin.freifunk.net/buildbot/feed/openwrt-19.07/). I didn't find anny issues with them by now. Until now, all targets got build fine.

@spolack Is the structure okay for you now?

2021-01-05 18:14 UTC, spolack commented on build_feed
> -  docker run --rm -it \
Before i approve or merge this i'd still like to see the parallel building not as default.

2021-01-05 18:16 UTC, spolack commented on build_all_targets
> +		(./build_feed "$SDK" "$FEED" "$OUTPUT_DIR") &
Either do it here and add -i to build_feed OR put the decision in build_feed.

2021-01-05 18:18 UTC, spolack commented
> Is the structure okay for you now?

There are still open comments from my side.


@PolynomialDivision  i dont agree that switching to other languages will be an improvement. But i thought parallel building could be also enabled through ENV Variables.

2021-01-05 22:50 UTC, Akira25 commented on build_all_targets
> +		(./build_feed "$SDK" "$FEED" "$OUTPUT_DIR") &
> If this flag is set, repo-builder won't run on buildbot. Technically it does not run on a shell there. Therefore -i wont work there.

@spolack is the -i rellay necessary? It would prevent running this script on buildbot. AFAICT the scripts builds sequentially even now, doesn't it?

2021-01-18 21:19 UTC, Akira25 commented
@spolack That should meet your expectation now. I'd like to avoid ENV-Variable on the buildbot.

2021-01-21 21:46 UTC, merged